spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:board
    driver-class-name: org.h2.Driver
    username: taekrigi
    password: taekrigi
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE